# Generated by Django 2.0.1 on 2020-03-04 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_auto_20200304_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('setar_nfe', 'Usuario pode alterar o parametro NF-e'), ('ver_dashboard', 'Pode visualizar o Dashboard'), ('permissao3', 'Permissao 3'))},
        ),
    ]
