# Generated by Django 2.0.1 on 2020-03-04 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_auto_20200304_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('deletar_clientes', 'Deletar clientes'),)},
        ),
        migrations.RemoveField(
            model_name='venda',
            name='max',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='media',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='media_desconto',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='min',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='num_ped_nefe',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='num_pedidos',
        ),
    ]
